#cloud-config

write_files:
  - path: /opt/test101/nginx.conf
    content: |
      worker_processes 1;
      events {
        worker_connections  1024;
      }
      http {
        include mime.types;
        default_type application/octet-stream;
        keepalive_timeout 65;
        gzip on;
        server {
          listen    80;
          server_name _;

          location / {
            proxy_pass http://10.4.0.200:5000;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
          }
        }
      }

coreos:
  units:
    - name: nginx.service
      command: restart
      content: |
        [Unit]
        Description=Nginx Reverse Proxy Service For Test101
        
        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker kill nginx-test101
        ExecStartPre=-/usr/bin/docker rm nginx-test101
        ExecStartPre=/usr/bin/docker pull nginx:mainline
        ExecStart=/usr/bin/docker run --name nginx-test101 -p 80:80 -v /opt/test101/nginx.conf:/etc/nginx/nginx.conf:ro -d nginx:mainline
