apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test101-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: test101
    spec:
      containers:
      - name: test101
        image: marenkovd/test101:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 3

